package com.aeotrade.provider.admin.uacVo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * @Author: yewei
 * @Date: 2020/1/7 22:26
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class StaffDto {

    private Long[] ids= new Long[]{};
    //@ApiModelProperty(value="手机号", allowEmptyValue=true)
    private String tel;
    //@ApiModelProperty(value="加入企业", allowEmptyValue=true)
    private List<MemberVO> member;

    //@Column(name="created_by", length=32)
    //@ApiModelProperty(value="创建人", allowEmptyValue=true)
    private String createdBy;

//    @AutoGenerated
//    @Column(name="created_time", length=29)
    //@ApiModelProperty(value="创建时间", allowEmptyValue=true)
    private java.sql.Timestamp createdTime;

    //@Column(name="dept", length=60)
    //@ApiModelProperty(value="部门", allowEmptyValue=true)
    private String dept;

    //@Id
    //@Column(name="id", length=19, nullable=false)
    //@ApiModelProperty(value="ID", allowEmptyValue=true)
    private Long id;

    //@Column(name="login_account", length=32)
    //@ApiModelProperty(value="登录帐号", allowEmptyValue=true)
    private String loginAccount;

    //@Column(name="login_paswd", length=128)
    //@ApiModelProperty(value="登录密码", allowEmptyValue=true)
    private String loginPaswd;

    //@Column(name="member_id", length=19)
    //@ApiModelProperty(value="企业ID", allowEmptyValue=true)
    private Long memberId;


    //@ApiModelProperty(value="乐观锁", allowEmptyValue=true)
    private Integer revision;


    //@ApiModelProperty(value="角色 管理员 :admin 普通员工:user", allowEmptyValue=true)
    private String role;


    //@ApiModelProperty(value="微信授权状态 未授权 0 ;已授权 1", allowEmptyValue=true)
    private Integer sgsStatus;


    //@ApiModelProperty(value="客服名称", allowEmptyValue=true)
    private String staffName;


    //@ApiModelProperty(value="启用状态", allowEmptyValue=true)
    private String staffStatus;


    //@ApiModelProperty(value="删除", allowEmptyValue=true)
    private Integer status;


    //@ApiModelProperty(value="更新人", allowEmptyValue=true)
    private String updatedBy;


    //@ApiModelProperty(value="更新时间", allowEmptyValue=true)
    private java.sql.Timestamp updatedTime;


    //@ApiModelProperty(value="头像", allowEmptyValue=true)
    private String wxLogo;


    private String wxOpenid;
}
