package com.aeotrade.provider.mamber.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.time.LocalDateTime;

/**
 * PmsCatalog频道栏目分类
 */
@TableName("pms_catalog")
@Generated("titan.lightbatis.web.generate.LombokBeanSerializer")
@Data
public class PmsCatalog {

    //@ApiModelProperty(value="导航栏", allowEmptyValue=true)
    //@Column(name="channel_section_id", length=10)
    private Integer channelSectionId;

    //@ApiModelProperty(value="创建人", allowEmptyValue=true)
    //@Column(name="created_by", length=10)
    private Integer createdBy;

    //@ApiModelProperty(value="创建时间", allowEmptyValue=true)
    //@Column(name="created_time", length=29)
    //@AutoGenerated
    private LocalDateTime createdTime;

    //@ApiModelProperty(value="描述", allowEmptyValue=true)
    //@Column(name="description", length=2147483647)
    private String description;

    //@ApiModelProperty(value="宽度", allowEmptyValue=true)
    //@Column(name="width", length=50)
    private String width;

    //@ApiModelProperty(value="是否为模块0否1是", allowEmptyValue=true)
    //@Column(name="is_moudle", length=10)
    private Integer isMoudle;


    //@ApiModelProperty(value="图标", allowEmptyValue=true)
    //@Column(name="icon")
    private String icon;

    //@ApiModelProperty(value="id", allowEmptyValue=true)
    //@Column(name="id", length=10, nullable=false)
    //@Id
    private Long id;

    //@ApiModelProperty(value="keywords", allowEmptyValue=true)
    //@Column(name="keywords")
    private String keywords;

    //@ApiModelProperty(value="分类级别：0->1级；1->2级", allowEmptyValue=true)
    //@Column(name="level", length=10)
    private Integer level;

    //@ApiModelProperty(value="企业ID", allowEmptyValue=true)
    //@Column(name="member_id", length=19)
    private Long memberId;

    //@ApiModelProperty(value="name", allowEmptyValue=true)
    //@Column(name="name", length=64)
    private String name;

    //@ApiModelProperty(value="模板名称", allowEmptyValue=true)
    //@Column(name="moudle_name", length=100)
    private String moudleName;

    //@ApiModelProperty(value="上机分类的编号：0表示一级分类", allowEmptyValue=true)
    //@Column(name="parent_id", length=19)
    private Long parentId;

    //@ApiModelProperty(value="乐观锁", allowEmptyValue=true)
    //@Column(name="revision", length=10)
    //@Revision
    private Integer revision;

    //@ApiModelProperty(value="显示状态：0->不显示；1->显示", allowEmptyValue=true)
    //@Column(name="" +"", length=10)
    private Integer showStatus;

    //@ApiModelProperty(value="sort", allowEmptyValue=true)
    //@Column(name="sort", length=10)
    private Integer sort;

    //@ApiModelProperty(value="删除", allowEmptyValue=true)
    //@LogicDelete
    //@Column(name="status", length=10)
    private Integer status;

    //@ApiModelProperty(value="更新人", allowEmptyValue=true)
    //@Column(name="updated_by", length=10)
    private Integer updatedBy;

    //@ApiModelProperty(value="更新时间", allowEmptyValue=true)
    //@Column(name="updated_time", length=29)
    //@AutoGenerated(event=titan.lightbatis.annotations.GeneratedEvent.Update)
    private LocalDateTime updatedTime;
}

