package com.aeotrade.provider.mamber.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * PmsColumn运营栏目配置表
 */
@TableName("pms_column")
@Data
public class PmsColumn {

    //@ApiModelProperty(value="开启状态,0未开启,1已开启", allowEmptyValue=true)
    //@Column(name="column_status", length=10, nullable=false)
    private Integer columnStatus;

    //@ApiModelProperty(value="创建时间", allowEmptyValue=true)
    //@AutoGenerated
    //@Column(name="create_time", length=19)
    private LocalDateTime createTime;

    //@ApiModelProperty(value="id", allowEmptyValue=true)
    //@Id
    //@Column(name="id", length=19, nullable=false)
    private Long id;

    //@ApiModelProperty(value="栏目名字", allowEmptyValue=true)
    //@Column(name="name", length=100, nullable=false)
    private String name;

    //@ApiModelProperty(value="上级id", allowEmptyValue=true)
    //@Column(name="parent_id", length=19, nullable=false)
    private Long parentId;

    //@ApiModelProperty(value="乐观锁", allowEmptyValue=true)
   // @Revision
    //@Column(name="revision", length=10)
    private Integer revision;

    //@ApiModelProperty(value="排序", allowEmptyValue=true)
    //@Column(name="sort", length=10)
    private Integer sort;

    //@LogicDelete
    //@ApiModelProperty(value="数据状态", allowEmptyValue=true)
    //@Column(name="status", length=10, nullable=false)
    private Integer status;

    //@ApiModelProperty(value="更新时间", allowEmptyValue=true)
    //@AutoGenerated(event=titan.lightbatis.annotations.GeneratedEvent.Update)
    //@Column(name="update_time", length=19)
    private LocalDateTime updateTime;


}

